spring.application.name=auth-service



server.port=8081

#database connection

spring.datasource.url=jdbc:postgresql://localhost:5432/event_booking_auth_db
spring.datasource.username=postgres
spring.datasource.password=Vereesh701

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
